settings:
  language-yaml: 'en.yml'
  boss-bar: #set as true if server version is 1.9 or higher
    active: true
    text: '&fAfter &e%distance% meters &fyou will reach point &a%waypoint_name% - %direction%'
    color: 'WHITE' #BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
    style: 'SOLID' #SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20, SOLID
  action-bar:
    active: true
    text: '&fAfter &e%distance% meters &fyou will reach point &a%waypoint_name% - %direction%'

hologram:
  height: 1.5
  lines:
    - '%waypoint_name%'
    - 'Your point is here.'